From java:8
MAINTAINER Hugo Guerra "hugoguerramelo@gmail.com"
EXPOSE 8085
COPY /var/lib/jenkins/workspace/generator-key-api-build/generator-key-app/target/generator-key-app.jar  generator-key-app.jar
ENTRYPOINT ["java","-jar","generator-key-app.jar"]
